repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        exclude: ^(yarn.lock|.yarn/|public/assets/logo/uimlogo.png)
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      # - id: no-commit-to-branch
      #   args: [--branch, main, --branch, master, --pattern, release/.*]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: ^(yarn.lock|.yarn/|.yarnrc.yml)

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: yarn run lint
        language: system

  - repo: local
    hooks:
      - id: prettier
        name: Prettier Format
        entry: yarn run prettier-fix
        language: system
