version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install
  build:
    commands:
      - set -eu
      - env | grep VITE
      - yarn build
      - aws s3 rm s3://${VITE_BUCKET_NAME}/ --recursive && aws s3 cp ./dist s3://${VITE_BUCKET_NAME}/ --recursive
