/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ContactList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Since we have custom orcabus_id prefix for each model, we need to remove the prefix before retrieving it. */
        get: operations["apiV1ContactRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact/{orcabusId}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the history of this model */
        get: operations["apiV1ContactHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/individual/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1IndividualList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/individual/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Since we have custom orcabus_id prefix for each model, we need to remove the prefix before retrieving it. */
        get: operations["apiV1IndividualRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/individual/{orcabusId}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the history of this model */
        get: operations["apiV1IndividualHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1LibraryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Since we have custom orcabus_id prefix for each model, we need to remove the prefix before retrieving it. */
        get: operations["apiV1LibraryRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{orcabusId}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the history of this model */
        get: operations["apiV1LibraryHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ProjectList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Since we have custom orcabus_id prefix for each model, we need to remove the prefix before retrieving it. */
        get: operations["apiV1ProjectRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project/{orcabusId}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the history of this model */
        get: operations["apiV1ProjectHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SampleList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Since we have custom orcabus_id prefix for each model, we need to remove the prefix before retrieving it. */
        get: operations["apiV1SampleRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/{orcabusId}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the history of this model */
        get: operations["apiV1SampleHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SubjectList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Since we have custom orcabus_id prefix for each model, we need to remove the prefix before retrieving it. */
        get: operations["apiV1SubjectRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/{orcabusId}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the history of this model */
        get: operations["apiV1SubjectHistoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        Contact: {
            readonly orcabusId: string;
            contactId?: string | null;
            name?: string | null;
            description?: string | null;
            /** Format: email */
            email?: string | null;
        };
        ContactDetail: {
            readonly orcabusId: string;
            readonly projectSet: components["schemas"]["Project"][];
            contactId?: string | null;
            name?: string | null;
            description?: string | null;
            /** Format: email */
            email?: string | null;
        };
        ContactHistory: {
            readonly historyId: number;
            readonly orcabusId: string;
            contactId?: string | null;
            name?: string | null;
            description?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: date-time */
            historyDate: string;
            historyChangeReason?: string | null;
            historyType: components["schemas"]["HistoryTypeEnum"];
            historyUser?: number | null;
        };
        /**
         * @description * `+` - Created
         *     * `~` - Changed
         *     * `-` - Deleted
         * @enum {string}
         */
        HistoryTypeEnum: "+" | "~" | "-";
        Individual: {
            readonly orcabusId: string;
            individualId?: string | null;
            source?: string | null;
        };
        IndividualDetail: {
            readonly orcabusId: string;
            readonly subjectSet: components["schemas"]["Subject"][];
            individualId?: string | null;
            source?: string | null;
        };
        IndividualHistory: {
            readonly historyId: number;
            readonly orcabusId: string;
            individualId?: string | null;
            source?: string | null;
            /** Format: date-time */
            historyDate: string;
            historyChangeReason?: string | null;
            historyType: components["schemas"]["HistoryTypeEnum"];
            historyUser?: number | null;
        };
        Library: {
            readonly orcabusId: string;
            libraryId?: string | null;
            phenotype?: (components["schemas"]["PhenotypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            workflow?: (components["schemas"]["WorkflowEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            quality?: (components["schemas"]["QualityEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            assay?: string | null;
            /** Format: double */
            coverage?: number | null;
            sample?: string | null;
            subject?: string | null;
        };
        LibraryDetail: {
            readonly orcabusId: string;
            readonly projectSet: components["schemas"]["Project"][];
            readonly sample: components["schemas"]["Sample"];
            readonly subject: components["schemas"]["Subject"];
            libraryId?: string | null;
            phenotype?: (components["schemas"]["PhenotypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            workflow?: (components["schemas"]["WorkflowEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            quality?: (components["schemas"]["QualityEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            assay?: string | null;
            /** Format: double */
            coverage?: number | null;
        };
        LibraryHistory: {
            readonly historyId: number;
            readonly projectSet: string[];
            readonly orcabusId: string;
            libraryId?: string | null;
            phenotype?: (components["schemas"]["PhenotypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            workflow?: (components["schemas"]["WorkflowEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            quality?: (components["schemas"]["QualityEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            assay?: string | null;
            /** Format: double */
            coverage?: number | null;
            /** Format: date-time */
            historyDate: string;
            historyChangeReason?: string | null;
            historyType: components["schemas"]["HistoryTypeEnum"];
            sample?: string | null;
            subject?: string | null;
            historyUser?: number | null;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedContactDetailList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["ContactDetail"][];
        };
        PaginatedContactHistoryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["ContactHistory"][];
        };
        PaginatedIndividualDetailList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["IndividualDetail"][];
        };
        PaginatedIndividualHistoryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["IndividualHistory"][];
        };
        PaginatedLibraryDetailList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["LibraryDetail"][];
        };
        PaginatedLibraryHistoryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["LibraryHistory"][];
        };
        PaginatedProjectDetailList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["ProjectDetail"][];
        };
        PaginatedProjectHistoryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["ProjectHistory"][];
        };
        PaginatedSampleDetailList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["SampleDetail"][];
        };
        PaginatedSampleHistoryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["SampleHistory"][];
        };
        PaginatedSubjectDetailList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["SubjectDetail"][];
        };
        PaginatedSubjectHistoryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["SubjectHistory"][];
        };
        /**
         * @description * `normal` - Normal
         *     * `tumor` - Tumor
         *     * `negative-control` - Negative Control
         * @enum {string}
         */
        PhenotypeEnum: "normal" | "tumor" | "negative-control";
        Project: {
            readonly orcabusId: string;
            projectId?: string | null;
            name?: string | null;
            description?: string | null;
        };
        ProjectDetail: {
            readonly orcabusId: string;
            readonly contactSet: components["schemas"]["Contact"][];
            readonly librarySet: components["schemas"]["Library"][];
            projectId?: string | null;
            name?: string | null;
            description?: string | null;
        };
        ProjectHistory: {
            readonly historyId: number;
            readonly contactSet: string[];
            readonly orcabusId: string;
            projectId?: string | null;
            name?: string | null;
            description?: string | null;
            /** Format: date-time */
            historyDate: string;
            historyChangeReason?: string | null;
            historyType: components["schemas"]["HistoryTypeEnum"];
            historyUser?: number | null;
        };
        /**
         * @description * `very-poor` - VeryPoor
         *     * `poor` - Poor
         *     * `good` - Good
         *     * `borderline` - Borderline
         * @enum {string}
         */
        QualityEnum: "very-poor" | "poor" | "good" | "borderline";
        Sample: {
            readonly orcabusId: string;
            sampleId?: string | null;
            externalSampleId?: string | null;
            source?: (components["schemas"]["SourceEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        SampleDetail: {
            readonly orcabusId: string;
            readonly librarySet: components["schemas"]["Library"][];
            sampleId?: string | null;
            externalSampleId?: string | null;
            source?: (components["schemas"]["SourceEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        SampleHistory: {
            readonly historyId: number;
            readonly orcabusId: string;
            sampleId?: string | null;
            externalSampleId?: string | null;
            source?: (components["schemas"]["SourceEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            historyDate: string;
            historyChangeReason?: string | null;
            historyType: components["schemas"]["HistoryTypeEnum"];
            historyUser?: number | null;
        };
        /**
         * @description * `ascites` - Ascites
         *     * `blood` - Blood
         *     * `bone-marrow` - BoneMarrow
         *     * `buccal` - Buccal
         *     * `cell-line` - Cell_line
         *     * `cfDNA` - Cfdna
         *     * `cyst-fluid` - Cyst Fluid
         *     * `DNA` - Dna
         *     * `eyebrow-hair` - Eyebrow Hair
         *     * `FFPE` - Ffpe
         *     * `FNA` - Fna
         *     * `OCT` - Oct
         *     * `organoid` - Organoid
         *     * `PDX-tissue` - Pdx Tissue
         *     * `plasma-serum` - Plasma Serum
         *     * `RNA` - Rna
         *     * `tissue` - Tissue
         *     * `skin` - Skin
         *     * `water` - Water
         * @enum {string}
         */
        SourceEnum: "ascites" | "blood" | "bone-marrow" | "buccal" | "cell-line" | "cfDNA" | "cyst-fluid" | "DNA" | "eyebrow-hair" | "FFPE" | "FNA" | "OCT" | "organoid" | "PDX-tissue" | "plasma-serum" | "RNA" | "tissue" | "skin" | "water";
        Subject: {
            readonly orcabusId: string;
            subjectId?: string | null;
        };
        SubjectDetail: {
            readonly orcabusId: string;
            readonly individualSet: components["schemas"]["Individual"][];
            readonly librarySet: components["schemas"]["Library"][];
            subjectId?: string | null;
        };
        SubjectHistory: {
            readonly historyId: number;
            readonly individualSet: string[];
            readonly orcabusId: string;
            subjectId?: string | null;
            /** Format: date-time */
            historyDate: string;
            historyChangeReason?: string | null;
            historyType: components["schemas"]["HistoryTypeEnum"];
            historyUser?: number | null;
        };
        /**
         * @description * `10X` - Ten X
         *     * `BiModal` - Bimodal
         *     * `ctDNA` - Ct Dna
         *     * `ctTSO` - Ct Tso
         *     * `exome` - Exome
         *     * `MeDIP` - Me Dip
         *     * `Metagenm` - Metagenm
         *     * `MethylSeq` - Methyl Seq
         *     * `TSO-DNA` - TSO_DNA
         *     * `TSO-RNA` - TSO_RNA
         *     * `WGS` - Wgs
         *     * `WTS` - Wts
         *     * `other` - Other
         * @enum {string}
         */
        TypeEnum: "10X" | "BiModal" | "ctDNA" | "ctTSO" | "exome" | "MeDIP" | "Metagenm" | "MethylSeq" | "TSO-DNA" | "TSO-RNA" | "WGS" | "WTS" | "other";
        /**
         * @description * `clinical` - Clinical
         *     * `research` - Research
         *     * `qc` - Qc
         *     * `control` - Control
         *     * `bcl` - Bcl
         *     * `manual` - Manual
         * @enum {string}
         */
        WorkflowEnum: "clinical" | "research" | "qc" | "control" | "bcl" | "manual";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apiV1ContactList: {
        parameters: {
            query?: {
                contactId?: string | null;
                description?: string | null;
                email?: string | null;
                name?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContactDetailList"];
                };
            };
        };
    };
    apiV1ContactRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this contact. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetail"];
                };
            };
        };
    };
    apiV1ContactHistoryList: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this contact. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContactHistoryList"];
                };
            };
        };
    };
    apiV1IndividualList: {
        parameters: {
            query?: {
                individualId?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                source?: string | null;
                subjectSet?: components["schemas"]["Subject"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIndividualDetailList"];
                };
            };
        };
    };
    apiV1IndividualRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this individual. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndividualDetail"];
                };
            };
        };
    };
    apiV1IndividualHistoryList: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this individual. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIndividualHistoryList"];
                };
            };
        };
    };
    apiV1LibraryList: {
        parameters: {
            query?: {
                assay?: string | null;
                coverage?: number | null;
                libraryId?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description * `normal` - Normal
                 *     * `tumor` - Tumor
                 *     * `negative-control` - Negative Control */
                phenotype?: "normal" | "tumor" | "negative-control" | "" | null;
                /** @description * `very-poor` - VeryPoor
                 *     * `poor` - Poor
                 *     * `good` - Good
                 *     * `borderline` - Borderline */
                quality?: "very-poor" | "poor" | "good" | "borderline" | "" | null;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                sample?: string | null;
                /** @description A search term. */
                search?: string;
                subject?: string | null;
                /** @description * `10X` - Ten X
                 *     * `BiModal` - Bimodal
                 *     * `ctDNA` - Ct Dna
                 *     * `ctTSO` - Ct Tso
                 *     * `exome` - Exome
                 *     * `MeDIP` - Me Dip
                 *     * `Metagenm` - Metagenm
                 *     * `MethylSeq` - Methyl Seq
                 *     * `TSO-DNA` - TSO_DNA
                 *     * `TSO-RNA` - TSO_RNA
                 *     * `WGS` - Wgs
                 *     * `WTS` - Wts
                 *     * `other` - Other */
                type?: "10X" | "BiModal" | "ctDNA" | "ctTSO" | "exome" | "MeDIP" | "Metagenm" | "MethylSeq" | "TSO-DNA" | "TSO-RNA" | "WGS" | "WTS" | "other" | "" | null;
                /** @description * `clinical` - Clinical
                 *     * `research` - Research
                 *     * `qc` - Qc
                 *     * `control` - Control
                 *     * `bcl` - Bcl
                 *     * `manual` - Manual */
                workflow?: "clinical" | "research" | "qc" | "control" | "bcl" | "manual" | "" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLibraryDetailList"];
                };
            };
        };
    };
    apiV1LibraryRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this library. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDetail"];
                };
            };
        };
    };
    apiV1LibraryHistoryList: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this library. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLibraryHistoryList"];
                };
            };
        };
    };
    apiV1ProjectList: {
        parameters: {
            query?: {
                description?: string | null;
                name?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                projectId?: string | null;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectDetailList"];
                };
            };
        };
    };
    apiV1ProjectRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this project. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    apiV1ProjectHistoryList: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this project. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectHistoryList"];
                };
            };
        };
    };
    apiV1SampleList: {
        parameters: {
            query?: {
                externalSampleId?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                sampleId?: string | null;
                /** @description A search term. */
                search?: string;
                /** @description * `ascites` - Ascites
                 *     * `blood` - Blood
                 *     * `bone-marrow` - BoneMarrow
                 *     * `buccal` - Buccal
                 *     * `cell-line` - Cell_line
                 *     * `cfDNA` - Cfdna
                 *     * `cyst-fluid` - Cyst Fluid
                 *     * `DNA` - Dna
                 *     * `eyebrow-hair` - Eyebrow Hair
                 *     * `FFPE` - Ffpe
                 *     * `FNA` - Fna
                 *     * `OCT` - Oct
                 *     * `organoid` - Organoid
                 *     * `PDX-tissue` - Pdx Tissue
                 *     * `plasma-serum` - Plasma Serum
                 *     * `RNA` - Rna
                 *     * `tissue` - Tissue
                 *     * `skin` - Skin
                 *     * `water` - Water */
                source?: "ascites" | "blood" | "bone-marrow" | "buccal" | "cell-line" | "cfDNA" | "cyst-fluid" | "DNA" | "eyebrow-hair" | "FFPE" | "FNA" | "OCT" | "organoid" | "PDX-tissue" | "plasma-serum" | "RNA" | "tissue" | "skin" | "water" | "" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSampleDetailList"];
                };
            };
        };
    };
    apiV1SampleRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this sample. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetail"];
                };
            };
        };
    };
    apiV1SampleHistoryList: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this sample. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSampleHistoryList"];
                };
            };
        };
    };
    apiV1SubjectList: {
        parameters: {
            query?: {
                /** @description Filter based on 'library_id' of the library associated with the subject. */
                libraryId?: string;
                /** @description Filter based on 'orcabus_id' of the library associated with the subject. */
                libraryOrcabusId?: string;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                subjectId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectDetailList"];
                };
            };
        };
    };
    apiV1SubjectRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this subject. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetail"];
                };
            };
        };
    };
    apiV1SubjectHistoryList: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this subject. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectHistoryList"];
                };
            };
        };
    };
}
