/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/library/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1LibraryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1LibraryRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{orcabusId}/full/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1LibraryFullRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/full/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1LibraryFullList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specimen/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SpecimenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specimen/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SpecimenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SubjectList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/{orcabusId}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SubjectRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/{orcabusId}/full/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["/api/v1/subject/id/full/"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject/full/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["/api/v1/subject/full/"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        Library: {
            readonly orcabusId: string;
            libraryId?: string | null;
            phenotype?: (components["schemas"]["PhenotypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            workflow?: (components["schemas"]["WorkflowEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            quality?: (components["schemas"]["QualityEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            assay?: string | null;
            /** Format: double */
            coverage?: number | null;
            projectOwner?: string | null;
            projectName?: string | null;
            specimen?: string | null;
        };
        /** @description This is a full Library serializer which include the specimen and subject models */
        LibraryFull: {
            readonly orcabusId: string;
            specimen: components["schemas"]["SpecimenSubject"];
            libraryId?: string | null;
            phenotype?: (components["schemas"]["PhenotypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            workflow?: (components["schemas"]["WorkflowEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            quality?: (components["schemas"]["QualityEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            assay?: string | null;
            /** Format: double */
            coverage?: number | null;
            projectOwner?: string | null;
            projectName?: string | null;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedLibraryFullList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["LibraryFull"][];
        };
        PaginatedLibraryList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["Library"][];
        };
        PaginatedSpecimenList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["Specimen"][];
        };
        PaginatedSubjectFullList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["SubjectFull"][];
        };
        PaginatedSubjectList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["Subject"][];
        };
        /**
         * @description * `normal` - Normal
         *     * `tumor` - Tumor
         *     * `negative-control` - Negative Control
         * @enum {string}
         */
        PhenotypeEnum: "normal" | "tumor" | "negative-control";
        /**
         * @description * `very-poor` - VeryPoor
         *     * `poor` - Poor
         *     * `good` - Good
         *     * `borderline` - Borderline
         * @enum {string}
         */
        QualityEnum: "very-poor" | "poor" | "good" | "borderline";
        /**
         * @description * `ascites` - Ascites
         *     * `blood` - Blood
         *     * `bone-marrow` - BoneMarrow
         *     * `buccal` - Buccal
         *     * `cell-line` - Cell_line
         *     * `cfDNA` - Cfdna
         *     * `cyst-fluid` - Cyst Fluid
         *     * `DNA` - Dna
         *     * `eyebrow-hair` - Eyebrow Hair
         *     * `FFPE` - Ffpe
         *     * `FNA` - Fna
         *     * `OCT` - Oct
         *     * `organoid` - Organoid
         *     * `PDX-tissue` - Pdx Tissue
         *     * `plasma-serum` - Plasma Serum
         *     * `RNA` - Rna
         *     * `tissue` - Tissue
         *     * `skin` - Skin
         *     * `water` - Water
         * @enum {string}
         */
        SourceEnum: "ascites" | "blood" | "bone-marrow" | "buccal" | "cell-line" | "cfDNA" | "cyst-fluid" | "DNA" | "eyebrow-hair" | "FFPE" | "FNA" | "OCT" | "organoid" | "PDX-tissue" | "plasma-serum" | "RNA" | "tissue" | "skin" | "water";
        Specimen: {
            readonly orcabusId: string;
            specimenId?: string | null;
            source?: (components["schemas"]["SourceEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            subject?: string | null;
        };
        /** @description This is a full Specimen serializer which include the library model */
        SpecimenLibrary: {
            readonly orcabusId: string;
            librarySet: components["schemas"]["Library"][];
            specimenId?: string | null;
            source?: (components["schemas"]["SourceEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            subject?: string | null;
        };
        /** @description This is a full Specimen serializer which include the subject model */
        SpecimenSubject: {
            readonly orcabusId: string;
            subject: components["schemas"]["Subject"];
            specimenId?: string | null;
            source?: (components["schemas"]["SourceEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        Subject: {
            readonly orcabusId: string;
            subjectId?: string | null;
        };
        /** @description This is a full Subject serializer which include all the children's (specimen and library) related models */
        SubjectFull: {
            readonly orcabusId: string;
            specimenSet: components["schemas"]["SpecimenLibrary"][];
            subjectId?: string | null;
        };
        /**
         * @description * `10X` - Ten X
         *     * `BiModal` - Bimodal
         *     * `ctDNA` - Ct Dna
         *     * `ctTSO` - Ct Tso
         *     * `exome` - Exome
         *     * `MeDIP` - Me Dip
         *     * `Metagenm` - Metagenm
         *     * `MethylSeq` - Methyl Seq
         *     * `TSO-DNA` - TSO_DNA
         *     * `TSO-RNA` - TSO_RNA
         *     * `WGS` - Wgs
         *     * `WTS` - Wts
         *     * `other` - Other
         * @enum {string}
         */
        TypeEnum: "10X" | "BiModal" | "ctDNA" | "ctTSO" | "exome" | "MeDIP" | "Metagenm" | "MethylSeq" | "TSO-DNA" | "TSO-RNA" | "WGS" | "WTS" | "other";
        /**
         * @description * `clinical` - Clinical
         *     * `research` - Research
         *     * `qc` - Qc
         *     * `control` - Control
         *     * `bcl` - Bcl
         *     * `manual` - Manual
         * @enum {string}
         */
        WorkflowEnum: "clinical" | "research" | "qc" | "control" | "bcl" | "manual";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apiV1LibraryList: {
        parameters: {
            query?: {
                assay?: string | null;
                coverage?: number | null;
                libraryId?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description * `normal` - Normal
                 *     * `tumor` - Tumor
                 *     * `negative-control` - Negative Control */
                phenotype?: "normal" | "tumor" | "negative-control" | "" | null;
                projectName?: string | null;
                projectOwner?: string | null;
                /** @description * `very-poor` - VeryPoor
                 *     * `poor` - Poor
                 *     * `good` - Good
                 *     * `borderline` - Borderline */
                quality?: "very-poor" | "poor" | "good" | "borderline" | "" | null;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                specimen?: string | null;
                /** @description * `10X` - Ten X
                 *     * `BiModal` - Bimodal
                 *     * `ctDNA` - Ct Dna
                 *     * `ctTSO` - Ct Tso
                 *     * `exome` - Exome
                 *     * `MeDIP` - Me Dip
                 *     * `Metagenm` - Metagenm
                 *     * `MethylSeq` - Methyl Seq
                 *     * `TSO-DNA` - TSO_DNA
                 *     * `TSO-RNA` - TSO_RNA
                 *     * `WGS` - Wgs
                 *     * `WTS` - Wts
                 *     * `other` - Other */
                type?: "10X" | "BiModal" | "ctDNA" | "ctTSO" | "exome" | "MeDIP" | "Metagenm" | "MethylSeq" | "TSO-DNA" | "TSO-RNA" | "WGS" | "WTS" | "other" | "" | null;
                /** @description * `clinical` - Clinical
                 *     * `research` - Research
                 *     * `qc` - Qc
                 *     * `control` - Control
                 *     * `bcl` - Bcl
                 *     * `manual` - Manual */
                workflow?: "clinical" | "research" | "qc" | "control" | "bcl" | "manual" | "" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLibraryList"];
                };
            };
        };
    };
    apiV1LibraryRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this library. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
        };
    };
    apiV1LibraryFullRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this library. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryFull"];
                };
            };
        };
    };
    apiV1LibraryFullList: {
        parameters: {
            query?: {
                assay?: string | null;
                coverage?: number | null;
                libraryId?: string | null;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description * `normal` - Normal
                 *     * `tumor` - Tumor
                 *     * `negative-control` - Negative Control */
                phenotype?: "normal" | "tumor" | "negative-control" | "" | null;
                projectName?: string | null;
                projectOwner?: string | null;
                /** @description * `very-poor` - VeryPoor
                 *     * `poor` - Poor
                 *     * `good` - Good
                 *     * `borderline` - Borderline */
                quality?: "very-poor" | "poor" | "good" | "borderline" | "" | null;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                specimen?: string | null;
                /** @description * `10X` - Ten X
                 *     * `BiModal` - Bimodal
                 *     * `ctDNA` - Ct Dna
                 *     * `ctTSO` - Ct Tso
                 *     * `exome` - Exome
                 *     * `MeDIP` - Me Dip
                 *     * `Metagenm` - Metagenm
                 *     * `MethylSeq` - Methyl Seq
                 *     * `TSO-DNA` - TSO_DNA
                 *     * `TSO-RNA` - TSO_RNA
                 *     * `WGS` - Wgs
                 *     * `WTS` - Wts
                 *     * `other` - Other */
                type?: "10X" | "BiModal" | "ctDNA" | "ctTSO" | "exome" | "MeDIP" | "Metagenm" | "MethylSeq" | "TSO-DNA" | "TSO-RNA" | "WGS" | "WTS" | "other" | "" | null;
                /** @description * `clinical` - Clinical
                 *     * `research` - Research
                 *     * `qc` - Qc
                 *     * `control` - Control
                 *     * `bcl` - Bcl
                 *     * `manual` - Manual */
                workflow?: "clinical" | "research" | "qc" | "control" | "bcl" | "manual" | "" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLibraryFullList"];
                };
            };
        };
    };
    apiV1SpecimenList: {
        parameters: {
            query?: {
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                /** @description * `ascites` - Ascites
                 *     * `blood` - Blood
                 *     * `bone-marrow` - BoneMarrow
                 *     * `buccal` - Buccal
                 *     * `cell-line` - Cell_line
                 *     * `cfDNA` - Cfdna
                 *     * `cyst-fluid` - Cyst Fluid
                 *     * `DNA` - Dna
                 *     * `eyebrow-hair` - Eyebrow Hair
                 *     * `FFPE` - Ffpe
                 *     * `FNA` - Fna
                 *     * `OCT` - Oct
                 *     * `organoid` - Organoid
                 *     * `PDX-tissue` - Pdx Tissue
                 *     * `plasma-serum` - Plasma Serum
                 *     * `RNA` - Rna
                 *     * `tissue` - Tissue
                 *     * `skin` - Skin
                 *     * `water` - Water */
                source?: "ascites" | "blood" | "bone-marrow" | "buccal" | "cell-line" | "cfDNA" | "cyst-fluid" | "DNA" | "eyebrow-hair" | "FFPE" | "FNA" | "OCT" | "organoid" | "PDX-tissue" | "plasma-serum" | "RNA" | "tissue" | "skin" | "water" | "" | null;
                specimenId?: string | null;
                subject?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSpecimenList"];
                };
            };
        };
    };
    apiV1SpecimenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this specimen. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Specimen"];
                };
            };
        };
    };
    apiV1SubjectList: {
        parameters: {
            query?: {
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                subjectId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectList"];
                };
            };
        };
    };
    apiV1SubjectRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this subject. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    "/api/v1/subject/id/full/": {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                /** @description A unique value identifying this subject. */
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectFullList"];
                };
            };
        };
    };
    "/api/v1/subject/full/": {
        parameters: {
            query?: {
                /** @description Filter the subjects that has the given library_id in the Library model. */
                libraryId?: string;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                /** @description A search term. */
                search?: string;
                subjectId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectFullList"];
                };
            };
        };
    };
}
