/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sequence/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SequenceList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sequence/{orcabusId}/comment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SequenceCommentList"];
        put?: never;
        post: operations["apiV1SequenceCommentCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sequence/{orcabusId}/comment/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["apiV1SequenceCommentPartialUpdate"];
        trace?: never;
    };
    "/api/v1/sequence/{orcabusId}/comment/{id}/soft_delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["apiV1SequenceCommentSoftDeleteDestroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sequence/{orcabusId}/state/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SequenceStateList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sequence/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1SequenceRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Comment: {
            orcabusId?: string;
            comment: string;
            associationId?: string;
            /** Format: date-time */
            readonly createdAt: string;
            createdBy: string;
            /** Format: date-time */
            readonly updatedAt: string;
            isDeleted?: boolean;
        };
        PaginatedSequenceList: {
            links: {
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=4
                 */
                next?: string | null;
                /**
                 * Format: uri
                 * @example http://api.example.org/accounts/?page=2
                 */
                previous?: string | null;
            };
            pagination: {
                count?: number;
                page?: number;
                rowsPerPage?: number;
            };
            results: components["schemas"]["Sequence"][];
        };
        PatchedComment: {
            orcabusId?: string;
            comment?: string;
            associationId?: string;
            /** Format: date-time */
            readonly createdAt?: string;
            createdBy?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            isDeleted?: boolean;
        };
        Sequence: {
            orcabusId?: string;
            instrumentRunId: string;
            runVolumeName: string;
            runFolderPath?: string | null;
            runDataUri: string;
            status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime?: string | null;
            reagentBarcode?: string | null;
            flowcellBarcode?: string | null;
            sampleSheetName?: string | null;
            sequenceRunId?: string | null;
            sequenceRunName?: string | null;
            v1pre3Id?: string | null;
            icaProjectId?: string | null;
            apiUrl?: string | null;
        };
        State: {
            orcabusId?: string;
            status: string;
            /** Format: date-time */
            timestamp: string;
            comment?: string | null;
            sequence: string;
        };
        /**
         * @description * `STARTED` - Started
         *     * `FAILED` - Failed
         *     * `SUCCEEDED` - Succeeded
         *     * `ABORTED` - Aborted
         * @enum {string}
         */
        StatusEnum: "STARTED" | "FAILED" | "SUCCEEDED" | "ABORTED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apiV1SequenceList: {
        parameters: {
            query?: {
                apiUrl?: string | null;
                endTime?: string | null;
                flowcellBarcode?: string | null;
                icaProjectId?: string | null;
                instrumentRunId?: string;
                orcabusId?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                reagentBarcode?: string | null;
                /** @description Number of results to return per page. */
                rowsPerPage?: number;
                runDataUri?: string;
                runFolderPath?: string | null;
                runVolumeName?: string;
                sampleSheetName?: string | null;
                /** @description A search term. */
                search?: string;
                sequenceRunId?: string | null;
                sequenceRunName?: string | null;
                startTime?: string;
                /** @description * `STARTED` - Started
                 *     * `FAILED` - Failed
                 *     * `SUCCEEDED` - Succeeded
                 *     * `ABORTED` - Aborted */
                status?: "STARTED" | "FAILED" | "SUCCEEDED" | "ABORTED";
                v1pre3Id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSequenceList"];
                };
            };
        };
    };
    apiV1SequenceCommentList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    apiV1SequenceCommentCreate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Comment"];
                "multipart/form-data": components["schemas"]["Comment"];
                "application/json": components["schemas"]["Comment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    apiV1SequenceCommentPartialUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["PatchedComment"];
                "multipart/form-data": components["schemas"]["PatchedComment"];
                "application/json": components["schemas"]["PatchedComment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    apiV1SequenceCommentSoftDeleteDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apiV1SequenceStateList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orcabusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"][];
                };
            };
        };
    };
    apiV1SequenceRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sequence"];
                };
            };
        };
    };
}
